<a href="https://colab.research.google.com/github/PrajwalRPrasad/pythonimages/blob/master/LAB_BOOK_2_18BBTCS086.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a=np.array(9)

print("Print A= ",a)

b=np.array([10,20,30])

print("Print B= ", b)

addition= np.add(a,b)

print("After Addition =", addition)

sub=np.subtract(b,a)

print("After Subtraction =",sub)

mul=np.multiply (a,b)

print("After Multiplcation =",mul)

div=np.divide (b,a)

print("After Division =",div)

div1=np.divide (b,5)

print("After Division =",div1)


Print A=  9
Print B=  [10 20 30]
After Addition = [19 29 39]
After Subtraction = [ 1 11 21]
After Multiplcation = [ 90 180 270]
After Division = [1.11111111 2.22222222 3.33333333]
After Division = [2. 4. 6.]


In [2]:
a= np.array([0.25,1.33,1,111])

print(a)

rec=np.reciprocal(a) 
print(rec)


[  0.25   1.33   1.   111.  ]
[4.         0.7518797  1.         0.00900901]


In [3]:
a=np.array([10,100,1000])

print(a)

pow=np.power(a,2)
print("after ^2 = ", pow)

b=np.array([2,3,1])

pow1=np.power(a,b)
print("after b array elements as ^ = ", pow1)


[  10  100 1000]
after ^2 =  [    100   10000 1000000]
after b array elements as ^ =  [    100 1000000    1000]


In [4]:
a= np.array ([10,20,30])
b= np.array ([3,5,7])

print("values of A=", a)
print("values of B=", b)

mm=np.mod(a,b)

rm=np.remainder(a,b)

print("values of MOD=", mm)
print("values of REMAINDER=", rm)


values of A= [10 20 30]
values of B= [3 5 7]
values of MOD= [1 0 2]
values of REMAINDER= [1 0 2]


In [5]:
a=np.array([-5.6j, 0.2j,11, 1+1j])
print(a)

print("real=",np.real(a))

print("imaginary=",np.imag(a))

print("Conjugate=", np.conj(a))


[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]
real= [-0.  0. 11.  1.]
imaginary= [-5.6  0.2  0.   1. ]
Conjugate= [-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


In [6]:
a=np.array ([1.0,5.3,123,0.56,25.5,32])

print(a)

print("after rounding up=", np.around(a))

print("after rounding up to 1st decimal value =", np.around(a,decimals=1))

[  1.     5.3  123.     0.56  25.5   32.  ]
after rounding up= [  1.   5. 123.   1.  26.  32.]
after rounding up to 1st decimal value = [  1.    5.3 123.    0.6  25.5  32. ]


In [7]:
a=np.array ([1.0,-5.3,123,-0.56,25.5,32])

print(a)

print('\n')

print(np.floor(a))

print(np.ceil(a))


[  1.    -5.3  123.    -0.56  25.5   32.  ]


[  1.  -6. 123.  -1.  25.  32.]
[  1.  -5. 123.  -0.  26.  32.]


In [8]:
import pandas as pd
import numpy as np

#Create a series with 100 random numbers
s = pd.Series(np.random.randn(4))
print (s)


0   -2.234304
1   -0.131866
2   -1.464326
3    0.859755
dtype: float64


In [9]:
import pandas as pd
import numpy as np

#Create a series with 100 random numbers
s = pd.Series(np.random.randn(4))
print ("The axes are:")
print (s.axes)


The axes are:
[RangeIndex(start=0, stop=4, step=1)]


In [10]:
import pandas as pd
import numpy as np
#Create a series with 100 random numbers
s = pd.Series(np.random.randn(4))
print ("Is the Object empty?")
print (s.empty)


Is the Object empty?
False


In [11]:
import pandas as pd
import numpy as np

#Create a series with 4 random numbers
s = pd.Series(np.random.randn(4))
print (s)

print ("The dimensions of the object:")
print (s.ndim)


0    1.751429
1    0.314127
2   -0.814821
3    1.166480
dtype: float64
The dimensions of the object:
1


In [12]:
import pandas as pd
import numpy as np

#Create a series with 4 random numbers
s = pd.Series(np.random.randn(2))
print (s)
print ("The size of the object:")
print (s.size)


0   -0.145152
1    0.135614
dtype: float64
The size of the object:
2


In [13]:
import pandas as pd
import numpy as np

#Create a series with 4 random numbers
s = pd.Series(np.random.randn(4))
print (s)

print ("The actual data series is:")
print (s.values)


0    0.776545
1    0.407317
2   -1.189349
3   -0.080074
dtype: float64
The actual data series is:
[ 0.77654457  0.40731724 -1.18934872 -0.08007425]


In [14]:
import pandas as pd
import numpy as np

#Create a series with 4 random numbers
s = pd.Series(np.random.randn(4))
print ("The original series is:")
print (s)

print ("The first two rows of the data series:")
print (s.head(2))


The original series is:
0   -0.783067
1    0.707303
2   -1.933227
3    0.060647
dtype: float64
The first two rows of the data series:
0   -0.783067
1    0.707303
dtype: float64


In [15]:
import pandas as pd
import numpy as np

#Create a series with 4 random numbers
s = pd.Series(np.random.randn(4))
print ("The original series is:")
print (s)

print ("The last two rows of the data series:")
print (s.tail(2))


The original series is:
0    0.898052
1   -2.269733
2   -0.839902
3   -0.227560
dtype: float64
The last two rows of the data series:
2   -0.839902
3   -0.227560
dtype: float64


In [16]:
import pandas as pd
import numpy as np

#Create a Dictionary of series
d = {'Name':pd.Series(['Rahul','Rohit','Virat','Surya','Shreyas','Rishab','Hardik']),
   'Age':pd.Series([25,26,25,23,30,29,23]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8])}

#Create a DataFrame
df = pd.DataFrame(d)
print ("Our data series is:")
print (df)


Our data series is:
      Name  Age  Rating
0    Rahul   25    4.23
1    Rohit   26    3.24
2    Virat   25    3.98
3    Surya   23    2.56
4  Shreyas   30    3.20
5   Rishab   29    4.60
6   Hardik   23    3.80
